// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MineralDeleteIFace is an autogenerated mock type for the MineralDeleteIFace type
type MineralDeleteIFace struct {
	mock.Mock
}

// Delete provides a mock function with given fields: mineralID
func (_m *MineralDeleteIFace) Delete(mineralID string) error {
	ret := _m.Called(mineralID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(mineralID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
