// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domain "github.com/manjdk/Carbon-Based-Life-Forms/domain"
	mock "github.com/stretchr/testify/mock"
)

// MineralsGetByClientIDIFace is an autogenerated mock type for the MineralsGetByClientIDIFace type
type MineralsGetByClientIDIFace struct {
	mock.Mock
}

// GetByClientID provides a mock function with given fields: clientID
func (_m *MineralsGetByClientIDIFace) GetByClientID(clientID string) ([]domain.Mineral, error) {
	ret := _m.Called(clientID)

	var r0 []domain.Mineral
	if rf, ok := ret.Get(0).(func(string) []domain.Mineral); ok {
		r0 = rf(clientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Mineral)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(clientID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
